#!/bin/bash
# vim: filetype=sh
# debug #set -x
MAPNAME=$1
MAPVIEW=/tmp/build/mapview
# TODO mapview -size
# store size and meta
# map data replace: mapreplace MAPFILE <input
MAPFILE=$(mktemp)

if [ -z "$EDITOR" ]; then 
    EDITOR=vim
fi

if [ -z "$MAPNAME" ]; then
    MAPNAME=./maps/map_1_1
fi

if [ ! -x "$MAPVIEW" ]; then
    (cd tools;make mapview)
fi

#cd ../ # TODO fix rel path problems
$MAPVIEW showmap $MAPNAME > $MAPFILE
#cd /tmp
$EDITOR $MAPFILE
#cat $MAPFILE | tr -d "\n" 
$MAPVIEW setmap $MAPNAME $MAPFILE
#$EDITOR $MAPNAME.new
BASE_MAPNAME=$(basename $MAPNAME)
mv $MAPNAME /tmp/$BASE_MAPNAME.old
mv /tmp/$BASE_MAPNAME.new $MAPNAME



